version: '3'
services:
  alpine:
    build: alpine/ 
    image: refinery29/alpine:3.7  
  markdown-search:
    build: markdown-search/
    image: refinery29/markdown-search
    ports:
      - "5000:5000"
    volumes:
      - ./data/docs:/wikis
